version: '3'

tasks:
  run:
    cmds:
      - doppler run -- pnpm dev

  debug:
    cmds:
      - doppler run -- clinic doctor -- node dist/src/index.js

  build:
    cmds:
      - docker build -t namhq1989/tapnchill-server:latest -t namhq1989/tapnchill-server:$(git rev-parse --short HEAD) .
      - docker push namhq1989/tapnchill-server:latest
      - docker push namhq1989/tapnchill-server:$(git rev-parse --short HEAD)
