// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/common/domain/report.go
//
// Generated by this command:
//
//	mockgen -source=pkg/common/domain/report.go -destination=internal/mock/common/report.go -package=mockcommon
//

// Package mockcommon is a generated GoMock package.
package mockcommon

import (
	reflect "reflect"

	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockReportRepository is a mock of ReportRepository interface.
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
	isgomock struct{}
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository.
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance.
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// NewUserFeedback mocks base method.
func (m *MockReportRepository) NewUserFeedback(ctx *appcontext.AppContext, feedbackID, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUserFeedback", ctx, feedbackID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// NewUserFeedback indicates an expected call of NewUserFeedback.
func (mr *MockReportRepositoryMockRecorder) NewUserFeedback(ctx, feedbackID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUserFeedback", reflect.TypeOf((*MockReportRepository)(nil).NewUserFeedback), ctx, feedbackID, content)
}
