// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/task/domain/service.go
//
// Generated by this command:
//
//	mockgen -source=pkg/task/domain/service.go -destination=internal/mock/task/service.go -package=mocktask
//

// Package mocktask is a generated GoMock package.
package mocktask

import (
	reflect "reflect"

	appcontext "github.com/namhq1989/go-utilities/appcontext"
	domain "github.com/namhq1989/tapnchill-server/pkg/task/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetGoalByID mocks base method.
func (m *MockService) GetGoalByID(ctx *appcontext.AppContext, goalID, userID string) (*domain.Goal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoalByID", ctx, goalID, userID)
	ret0, _ := ret[0].(*domain.Goal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGoalByID indicates an expected call of GetGoalByID.
func (mr *MockServiceMockRecorder) GetGoalByID(ctx, goalID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoalByID", reflect.TypeOf((*MockService)(nil).GetGoalByID), ctx, goalID, userID)
}

// GetTaskByID mocks base method.
func (m *MockService) GetTaskByID(ctx *appcontext.AppContext, taskID, userID string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, taskID, userID)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockServiceMockRecorder) GetTaskByID(ctx, taskID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockService)(nil).GetTaskByID), ctx, taskID, userID)
}
