// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/user/domain/report.go
//
// Generated by this command:
//
//	mockgen -source=pkg/user/domain/report.go -destination=internal/mock/user/report.go -package=mockuser
//

// Package mockuser is a generated GoMock package.
package mockuser

import (
	reflect "reflect"

	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockReportRepository is a mock of ReportRepository interface.
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
	isgomock struct{}
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository.
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance.
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// NewUserSignedInWithGoogle mocks base method.
func (m *MockReportRepository) NewUserSignedInWithGoogle(ctx *appcontext.AppContext, userID, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUserSignedInWithGoogle", ctx, userID, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// NewUserSignedInWithGoogle indicates an expected call of NewUserSignedInWithGoogle.
func (mr *MockReportRepositoryMockRecorder) NewUserSignedInWithGoogle(ctx, userID, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUserSignedInWithGoogle", reflect.TypeOf((*MockReportRepository)(nil).NewUserSignedInWithGoogle), ctx, userID, email)
}
