// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: userpb/hub.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHabitQuotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId string `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetHabitQuotaRequest) Reset() {
	*x = GetHabitQuotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userpb_hub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHabitQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitQuotaRequest) ProtoMessage() {}

func (x *GetHabitQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_hub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetHabitQuotaRequest) Descriptor() ([]byte, []int) {
	return file_userpb_hub_proto_rawDescGZIP(), []int{0}
}

func (x *GetHabitQuotaRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetHabitQuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetHabitQuotaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetHabitQuotaResponse) Reset() {
	*x = GetHabitQuotaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userpb_hub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHabitQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHabitQuotaResponse) ProtoMessage() {}

func (x *GetHabitQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_hub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHabitQuotaResponse.ProtoReflect.Descriptor instead.
func (*GetHabitQuotaResponse) Descriptor() ([]byte, []int) {
	return file_userpb_hub_proto_rawDescGZIP(), []int{1}
}

func (x *GetHabitQuotaResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetGoalQuotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId string `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetGoalQuotaRequest) Reset() {
	*x = GetGoalQuotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userpb_hub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoalQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalQuotaRequest) ProtoMessage() {}

func (x *GetGoalQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_hub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetGoalQuotaRequest) Descriptor() ([]byte, []int) {
	return file_userpb_hub_proto_rawDescGZIP(), []int{2}
}

func (x *GetGoalQuotaRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetGoalQuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetGoalQuotaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetGoalQuotaResponse) Reset() {
	*x = GetGoalQuotaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userpb_hub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoalQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoalQuotaResponse) ProtoMessage() {}

func (x *GetGoalQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_hub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoalQuotaResponse.ProtoReflect.Descriptor instead.
func (*GetGoalQuotaResponse) Descriptor() ([]byte, []int) {
	return file_userpb_hub_proto_rawDescGZIP(), []int{3}
}

func (x *GetGoalQuotaResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTaskQuotaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId string `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetTaskQuotaRequest) Reset() {
	*x = GetTaskQuotaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userpb_hub_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskQuotaRequest) ProtoMessage() {}

func (x *GetTaskQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_hub_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskQuotaRequest.ProtoReflect.Descriptor instead.
func (*GetTaskQuotaRequest) Descriptor() ([]byte, []int) {
	return file_userpb_hub_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskQuotaRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *GetTaskQuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTaskQuotaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetTaskQuotaResponse) Reset() {
	*x = GetTaskQuotaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_userpb_hub_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskQuotaResponse) ProtoMessage() {}

func (x *GetTaskQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userpb_hub_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskQuotaResponse.ProtoReflect.Descriptor instead.
func (*GetTaskQuotaResponse) Descriptor() ([]byte, []int) {
	return file_userpb_hub_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskQuotaResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_userpb_hub_proto protoreflect.FileDescriptor

var file_userpb_hub_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x2f, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x22, 0x48, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x48, 0x61, 0x62, 0x69, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74,
	0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x47, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x51, 0x75,
	0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x47, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75,
	0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x32, 0xf7, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x48, 0x61, 0x62, 0x69, 0x74, 0x51, 0x75, 0x6f,
	0x74, 0x61, 0x12, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x48,
	0x61, 0x62, 0x69, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x62,
	0x69, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x12, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f,
	0x61, 0x6c, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x61, 0x6c, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x12, 0x1b,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x6f, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x77, 0x0a, 0x0a, 0x63,
	0x6f, 0x6d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x42, 0x08, 0x48, 0x75, 0x62, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x27, 0x74, 0x61, 0x70, 0x6e, 0x63, 0x68, 0x69, 0x6c, 0x6c,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x70, 0x62, 0xa2, 0x02,
	0x03, 0x55, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x55, 0x73, 0x65, 0x72, 0x70, 0x62, 0xca, 0x02, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x70, 0x62, 0xe2, 0x02, 0x12, 0x55, 0x73, 0x65, 0x72, 0x70, 0x62, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_userpb_hub_proto_rawDescOnce sync.Once
	file_userpb_hub_proto_rawDescData = file_userpb_hub_proto_rawDesc
)

func file_userpb_hub_proto_rawDescGZIP() []byte {
	file_userpb_hub_proto_rawDescOnce.Do(func() {
		file_userpb_hub_proto_rawDescData = protoimpl.X.CompressGZIP(file_userpb_hub_proto_rawDescData)
	})
	return file_userpb_hub_proto_rawDescData
}

var file_userpb_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_userpb_hub_proto_goTypes = []interface{}{
	(*GetHabitQuotaRequest)(nil),  // 0: userpb.GetHabitQuotaRequest
	(*GetHabitQuotaResponse)(nil), // 1: userpb.GetHabitQuotaResponse
	(*GetGoalQuotaRequest)(nil),   // 2: userpb.GetGoalQuotaRequest
	(*GetGoalQuotaResponse)(nil),  // 3: userpb.GetGoalQuotaResponse
	(*GetTaskQuotaRequest)(nil),   // 4: userpb.GetTaskQuotaRequest
	(*GetTaskQuotaResponse)(nil),  // 5: userpb.GetTaskQuotaResponse
}
var file_userpb_hub_proto_depIdxs = []int32{
	0, // 0: userpb.UserService.GetHabitQuota:input_type -> userpb.GetHabitQuotaRequest
	2, // 1: userpb.UserService.GetGoalQuota:input_type -> userpb.GetGoalQuotaRequest
	4, // 2: userpb.UserService.GetTaskQuota:input_type -> userpb.GetTaskQuotaRequest
	1, // 3: userpb.UserService.GetHabitQuota:output_type -> userpb.GetHabitQuotaResponse
	3, // 4: userpb.UserService.GetGoalQuota:output_type -> userpb.GetGoalQuotaResponse
	5, // 5: userpb.UserService.GetTaskQuota:output_type -> userpb.GetTaskQuotaResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_userpb_hub_proto_init() }
func file_userpb_hub_proto_init() {
	if File_userpb_hub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_userpb_hub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHabitQuotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userpb_hub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHabitQuotaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userpb_hub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoalQuotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userpb_hub_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoalQuotaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userpb_hub_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskQuotaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_userpb_hub_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskQuotaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userpb_hub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userpb_hub_proto_goTypes,
		DependencyIndexes: file_userpb_hub_proto_depIdxs,
		MessageInfos:      file_userpb_hub_proto_msgTypes,
	}.Build()
	File_userpb_hub_proto = out.File
	file_userpb_hub_proto_rawDesc = nil
	file_userpb_hub_proto_goTypes = nil
	file_userpb_hub_proto_depIdxs = nil
}
